-- schema.sql ------------------------------------

-- Institutions ----------------------------------
CREATE TABLE `institutions_main` (
  `UNITID` INT NOT NULL PRIMARY KEY,
  `INSTNM` VARCHAR(255),
  `CITY` VARCHAR(100),
  `STABBR` VARCHAR(2),
  `ZIP` VARCHAR(20),
  `ACCREDAGENCY` VARCHAR(255),
  `INSTURL` VARCHAR(255),
  `NPCURL` VARCHAR(255),
  `MAIN` INT DEFAULT NULL,
  `NUMBRANCH` INT DEFAULT NULL,
  `PREDDEG` INT DEFAULT NULL,
  `CONTROL` INT DEFAULT NULL,
  `ST_FIPS` INT DEFAULT NULL,
  `LATITUDE` FLOAT DEFAULT NULL,
  `LONGITUDE` FLOAT DEFAULT NULL,
  `ADM_RATE` FLOAT,
  `ACTCMMID` FLOAT,
  `SAT_AVG` FLOAT,
  `CURROPER` INT DEFAULT NULL,
  `NPT4_PUB` INT,
  `NPT4_PRIV` INT,
  `NUM4_PUB` INT,
  `NUM4_PRIV` INT,
  `COSTT4_A` INT,
  `PCTFLOAN` FLOAT DEFAULT NULL,
  `UG25ABV` FLOAT DEFAULT NULL,
  `COMP_ORIG_YR2_RT` FLOAT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Programs ----------------------------------
CREATE TABLE `programs_main` (
  `UNITID` INT NOT NULL,
  `CONTROL` VARCHAR(10),
  `CIPCODE` VARCHAR(50),
  `CIPDESC` VARCHAR(255),
  `CREDLEV` INT,
  `CREDDESC` VARCHAR(100),
  `DEBT_ALL_PP_EVAL_MEAN` INT,
  `DEBT_ALL_STGP_EVAL_MEAN` INT,
  `EARN_COUNT_NWNE_HI_1YR` INT,
  `EARN_COUNT_WNE_HI_1YR` INT,
  `EARN_MDN_HI_1YR` INT,
  `EARN_COUNT_NWNE_HI_2YR` INT,
  `EARN_COUNT_WNE_HI_2YR` INT,
  `EARN_MDN_HI_2YR` INT,
  PRIMARY KEY(UNITID, CIPCODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Users ----------------------------------
CREATE TABLE `users_main` (
  `id` INT NOT NULL,
  `name` VARCHAR(40),
  `email` VARCHAR(50),
  `gender` VARCHAR(1),
  `address` VARCHAR(50),
  `state` VARCHAR(2),
  `latitude` FLOAT DEFAULT NULL,
  `longitude` FLOAT DEFAULT NULL,
  `GPA` FLOAT DEFAULT NULL,
  `SAT` INT,
  `ACT` INT,
  `min_ROI` FLOAT DEFAULT NULL,
  `high_school_major` VARCHAR(20),
  `preferred_degree_type` VARCHAR(50),
  `preferred_field_category` VARCHAR(20),
  PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

